### ISSUE TITLE
CRAB and CKTON logos need to be changed

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/darwinia2.0-account-migration-ui#18]
<img width="639" alt="image" src="https://user-images.githubusercontent.com/80877629/224205147-ebe09828-114d-49f9-b8be-428614693901.png">
https://migration-ui-stg.vercel.app/#/migration?network=Crab

**Comment by isunaslabs** [comment]
@1022ranji I need the required icons

**Comment by 1022ranji** [comment]
done
