### ISSUE TITLE
A way to support other polkadot wallets

### ISSUE THREAD

**Issue by wuminzhe** [darwinia-network/darwinia2.0-account-migration-ui#9]
```typescript
window.injectedWeb3["polkadot-js"] = window.injectedWeb3["talisman"];
```

**Comment by wuminzhe** [comment]
Seems like the ui has already supported multi polkadot wallets. 

<img width="664" alt="image" src="https://user-images.githubusercontent.com/1608576/223064684-e3ac4ab6-cdc0-42ca-bead-4cacb095686a.png">

All we have to do may be to remove the polkadot-js checking code.

**Comment by 1022ranji** [comment]
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/80877629/234463451-ec90d985-2cf2-4576-a782-31bc421e3385.png">
